//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MsgPack
{
    [Serializable]
    public class UwbDistanceMsg : Message
    {
        public const string k_RosMessageName = "msg_pack/UwbDistance";
        public override string RosMessageName => k_RosMessageName;

        public sbyte beacon_id;
        public float range;

        public UwbDistanceMsg()
        {
            this.beacon_id = 0;
            this.range = 0.0f;
        }

        public UwbDistanceMsg(sbyte beacon_id, float range)
        {
            this.beacon_id = beacon_id;
            this.range = range;
        }

        public static UwbDistanceMsg Deserialize(MessageDeserializer deserializer) => new UwbDistanceMsg(deserializer);

        private UwbDistanceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.beacon_id);
            deserializer.Read(out this.range);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.beacon_id);
            serializer.Write(this.range);
        }

        public override string ToString()
        {
            return "UwbDistanceMsg: " +
            "\nbeacon_id: " + beacon_id.ToString() +
            "\nrange: " + range.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
