//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class Fly_velocityMsg : Message
    {
        public const string k_RosMessageName = "Scripts/fly_velocity";
        public override string RosMessageName => k_RosMessageName;

        public float v_x;
        public float v_y;
        public float v_z;

        public Fly_velocityMsg()
        {
            this.v_x = 0.0f;
            this.v_y = 0.0f;
            this.v_z = 0.0f;
        }

        public Fly_velocityMsg(float v_x, float v_y, float v_z)
        {
            this.v_x = v_x;
            this.v_y = v_y;
            this.v_z = v_z;
        }

        public static Fly_velocityMsg Deserialize(MessageDeserializer deserializer) => new Fly_velocityMsg(deserializer);

        private Fly_velocityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.v_x);
            deserializer.Read(out this.v_y);
            deserializer.Read(out this.v_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.v_x);
            serializer.Write(this.v_y);
            serializer.Write(this.v_z);
        }

        public override string ToString()
        {
            return "Fly_velocityMsg: " +
            "\nv_x: " + v_x.ToString() +
            "\nv_y: " + v_y.ToString() +
            "\nv_z: " + v_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
