//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class Range_sensorMsg : Message
    {
        public const string k_RosMessageName = "Scripts/range_sensor";
        public override string RosMessageName => k_RosMessageName;

        public sbyte sensor_id;
        public float range;

        public Range_sensorMsg()
        {
            this.sensor_id = 0;
            this.range = 0.0f;
        }

        public Range_sensorMsg(sbyte sensor_id, float range)
        {
            this.sensor_id = sensor_id;
            this.range = range;
        }

        public static Range_sensorMsg Deserialize(MessageDeserializer deserializer) => new Range_sensorMsg(deserializer);

        private Range_sensorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sensor_id);
            deserializer.Read(out this.range);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sensor_id);
            serializer.Write(this.range);
        }

        public override string ToString()
        {
            return "Range_sensorMsg: " +
            "\nsensor_id: " + sensor_id.ToString() +
            "\nrange: " + range.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
