//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class TakeoffMsg : Message
    {
        public const string k_RosMessageName = "Scripts/takeoff";
        public override string RosMessageName => k_RosMessageName;

        public float height;

        public TakeoffMsg()
        {
            this.height = 0.0f;
        }

        public TakeoffMsg(float height)
        {
            this.height = height;
        }

        public static TakeoffMsg Deserialize(MessageDeserializer deserializer) => new TakeoffMsg(deserializer);

        private TakeoffMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.height);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.height);
        }

        public override string ToString()
        {
            return "TakeoffMsg: " +
            "\nheight: " + height.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
