//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class UWB_distanceMsg : Message
    {
        public const string k_RosMessageName = "Scripts/UWB_distance";
        public override string RosMessageName => k_RosMessageName;

        public sbyte beacon_id;
        public float range;

        public UWB_distanceMsg()
        {
            this.beacon_id = 0;
            this.range = 0.0f;
        }

        public UWB_distanceMsg(sbyte beacon_id, float range)
        {
            this.beacon_id = beacon_id;
            this.range = range;
        }

        public static UWB_distanceMsg Deserialize(MessageDeserializer deserializer) => new UWB_distanceMsg(deserializer);

        private UWB_distanceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.beacon_id);
            deserializer.Read(out this.range);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.beacon_id);
            serializer.Write(this.range);
        }

        public override string ToString()
        {
            return "UWB_distanceMsg: " +
            "\nbeacon_id: " + beacon_id.ToString() +
            "\nrange: " + range.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
